version: "3"
services:
    broker:
        image: eclipse-mosquitto:2.0
        volumes:
         - ./mosquitto/config:/mosquitto/config
         - ./mosquitto/data:/mosquitto/data 
         - ./mosquitto/log:/mosquitto/log
    subscriber:
        image: python:3.9
        volumes:
          - ./src:/home/src
        tty: true
    publisher:
        image: python:3.9
        volumes:
          - ./src:/home/src
        tty: true